version: 0
protection-types: [ "private", "display", "deposit", "withdrawal", "public" ]
access-types:
  private: [ ]
  display: [ "interact", "open" ]
  deposit: [ "interact", "open", "deposit" ]
  withdrawal: [ "interact", "open", "withdraw" ]
  public: [ "interact", "open", "deposit", "withdraw", "place", "spawn", "modify" ]
  basic: [ "interact", "open", "deposit", "withdraw", "place", "spawn", "modify" ]
  full: [ "interact", "open", "deposit", "withdraw", "place", "break", "spawn", "kill", "modify", "edit" ]
