version: 0
language: en
protection-types: [ "private", "display", "deposit", "withdrawal", "public" ]
access-types:
  private: [ ]
  display: [ "interact", "open" ]
  deposit: [ "interact", "open", "deposit" ]
  withdrawal: [ "interact", "open", "withdraw" ]
  redstone: [ "redstone" ]
  public: [ "interact", "open", "deposit", "withdraw", "mount" ]
  basic: [ "interact", "open", "deposit", "withdraw", "mount" ]
  full: [ "interact", "open", "deposit", "withdraw", "mount", "edit", "destroy" ]
blocks:
  chest: private
  trapped_chest: private
  furnace: private
  blast_furnace: private
  smoker: private
  dispenser: private
  dropper: private
  barrel: private
  composter: private
  lectern: private
  shulker_box: private
  white_shulker_box: private
  orange_shulker_box: private
  magenta_shulker_box: private
  light_blue_shulker_box: private
  yellow_shulker_box: private
  lime_shulker_box: private
  pink_shulker_box: private
  gray_shulker_box: private
  light_gray_shulker_box: private
  cyan_shulker_box: private
  purple_shulker_box: private
  blue_shulker_box: private
  brown_shulker_box: private
  green_shulker_box: private
  red_shulker_box: private
  black_shulker_box: private
  sign: none
  iron_door: none
  oak_door: none
  spruce_door: none
  birch_door: none
  jungle_door: none
  acacia_door: none
  dark_oak_door: none
  crimson_door: none
  warped_door: none
  iron_trapdoor: none
  oak_trapdoor: none
  spruce_trapdoor: none
  birch_trapdoor: none
  jungle_trapdoor: none
  acacia_trapdoor: none
  dark_oak_trapdoor: none
  crimson_trapdoor: none
  warped_trapdoor: none
  oak_fence_gate: none
  spruce_fence_gate: none
  birch_fence_gate: none
  jungle_fence_gate: none
  acacia_fence_gate: none
  dark_oak_fence_gate: none
  crimson_fence_gate: none
  warped_fence_gate: none
  white_banner: none
  orange_banner: none
  magenta_banner: none
  light_blue_banner: none
  yellow_banner: none
  lime_banner: none
  pink_banner: none
  gray_banner: none
  light_gray_banner: none
  cyan_banner: none
  purple_banner: none
  blue_banner: none
  brown_banner: none
  green_banner: none
  red_banner: none
  black_banner: none
  white_wall_banner: none
  orange_wall_banner: none
  magenta_wall_banner: none
  light_blue_wall_banner: none
  yellow_wall_banner: none
  lime_wall_banner: none
  pink_wall_banner: none
  gray_wall_banner: none
  light_gray_wall_banner: none
  cyan_wall_banner: none
  purple_wall_banner: none
  blue_wall_banner: none
  brown_wall_banner: none
  green_wall_banner: none
  red_wall_banner: none
  black_wall_banner: none
entities:
  armor_stand: private
  item_frame: private
  glow_item_frame: private
