name: ${name}
version: ${version}
main: ${group}.bolt.BoltPlugin
api-version: 1.13
authors: [${author}]
description: ${description}
commands:
  bolt:
    description: Main bolt command
    permission: bolt.command
  lock:
    description: Shortcut lock command for convenience
    permission: bolt.command.lock
  unlock:
    description: Shortcut unlock command for convenience
    permission: bolt.command.unlock
permissions:
  bolt.admin:
    default: false
  bolt.command:
    default: true
  bolt.command.admin:
    default: op
  bolt.command.edit:
    default: true
  bolt.command.group:
    default: true
  bolt.command.info:
    default: true
  bolt.command.lock:
    default: true
  bolt.command.mode:
    default: true
  bolt.command.password:
    default: true
  bolt.command.transfer:
    default: true
  bolt.command.trust:
    default: true
  bolt.command.unlock:
    default: true
  bolt.protection.notify:
    default: false
